repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --diff
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: autoflake
        name: autoflake
        entry: autoflake .
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 --config .flake8
        language: system
        types: [python]

      - id: pyright
        name: pyright
        entry: pyright .
        language: system
        types: [python]
        